accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "MPL-2.0",
    "Zlib",
    "BSL-1.0",
]

targets = [
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-ios",
    "aarch64-apple-darwin",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
no-clearly-defined = true
private = { ignore = true }
